#!/usr/bin/env bash
# Digging into the given domain and extracting the information.

print () {
    dig "$1" | grep -A1 'ANSWER SECTION:' | sed -r "s/$1./$2/g" | awk -F" " ' NR==2 { print "The subdomain " $1 " is a " $4 " record and points to " $5 }'
}
if [ "$#" -lt 3 ]
then
    print "$2.$1" "$2"
else
    print "www.$1" "www"
    print "lb-01.$1" "lb-01"
    print "web-02.$1" "web-02"
    print "web-01.$1" "web-01"
fi
