#!/usr/bin/env bash
# This script configures a new Ubuntu machine to respect the requirements asked in the task.
sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx start
