#!/usr/bin/env bash
# This script configures a new Ubuntu machine to load balance between two servers.
sudo apt-get -y update
sudo apt-get -y install haproxy
mkdir -p ~/config
cp /etc/haproxy/haproxy.cfg ~/config/haproxy.cfg.backup
echo "
frontend forward
    bind *:80
    mode http
    timeout client 30s
    default_backend wings
backend wings
    timeout connect 10s
    timeout server 30s
    mode http
    balance roundrobin
    server server-1 100.26.237.224
    server server-2 100.25.204.41
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
