#!/usr/bin/env bash
# This script will configure nginx to listen on port 80.
cd /etc/nginx/sites-enabled/ || exit;
rm default;
ln -s /etc/nginx/sites-available/default default;
# Restarting nginx.
sudo service nginx restart
