#!/usr/bin/env bash
# This script kills script 4* process.
# shellcheck disable=SC2009

trap "echo 'I hate the kill command' && rm /var/run/myscript.pid && exit" 15
trap "echo 'Y U no love me?!'" 2
trap "rm /var/run/myscript.pid && exit" 3

echo $$ > /var/run/myscript.pid
while true
do
	echo "To infinity and beyond"
	sleep 2
done
