#!/usr/bin/env bash
# This script is used to run nginx server as nginx user.
# Fix the permission issues with nginx user.
# Stops apache server if it is running.

sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
